import { IConfiguration } from "../typings";

export const defaultConfiguration: IConfiguration = {
    chatServer: "/botman",
    frameEndpoint: "/botman/chat",
    timeFormat: "HH:MM",
    dateTimeFormat: "m/d/yy HH:MM",
    title: "BUZZ",
    cookieValidInDays: 1,
    introMessage: "",
    placeholderText: "Send a message...",
    displayMessageTime: true,
    sendWidgetOpenedEvent: false,
    widgetOpenedEventData: "",
    mainColor: "white",
    headerTextColor: "#333",
    bubbleBackground: "black", //closed mobile button color
    bubbleAvatarUrl:
        "https://ripemetrics.com/assets/images/chatbot/chatbubble.svg",
    desktopHeight: 450,
    desktopWidth: 370,
    mobileHeight: "100%",
    mobileWidth: "300px",
    videoHeight: 160,
    aboutLink: "https://ripemetrics.com",
    aboutText: "Powered by 🍊 RipeMetrics",
    chatId: "",
    userId: "",
    alwaysUseFloatingButton: false,
    useEcho: false,
    echoChannel: (userId: string) => "",
    echoConfiguration: {},
    echoEventName: ".message.created",
    echoChannelType: "private",
};
