import { IConfiguration } from "../typings";

export const defaultConfiguration: IConfiguration = {
    chatServer: "/botman",
    frameEndpoint: "/botman/chat",
    timeFormat: "HH:MM",
    dateTimeFormat: "m/d/yy HH:MM",
    title: "",
    cookieValidInDays: 1,
    introMessage: "",
    placeholderText: "Send a message...",
    displayMessageTime: true,
    sendWidgetOpenedEvent: false,
    widgetOpenedEventData: "",
    mainColor: "white",
    headerTextColor: "#333",
    bubbleBackground: "black", //closed mobile button color
    bubbleAvatarUrl:
        "https://buzzdelivery.org/wp-content/uploads/2021/04/logo_footer_v2.png",
    desktopHeight: 450,
    desktopWidth: 370,
    mobileHeight: "100%",
    mobileWidth: "300px",
    videoHeight: 160,
    aboutLink: "https://botman.io",
    aboutText: "⚡ Powered by Botman and Ripemetrics",
    chatId: "",
    userId: "",
    alwaysUseFloatingButton: false,
    useEcho: false,
    echoChannel: (userId: string) => "",
    echoConfiguration: {},
    echoEventName: ".message.created",
    echoChannelType: "private",
};
